### ISSUE TITLE
FoodClassification example does not run

### ISSUE THREAD

**Issue by choowilson** [CertifaiAI/cdle-traininglabs#62]
FoodClassification example has a few problems:
1. Use wrong iterator
2. No dataset
3. Does not safely state the path of dataset.(will fail on Linux)

**Comment by chiaweilim** [comment]
https://github.com/CertifaiAI/TrainingLabs/blob/master/dl4j-cv-labs/src/main/java/global/skymind/solution/classification/FoodClassification.java#L76-L78

This is not intended. There's FoodDataSetIterator in the same folder which is not being used.

**Comment by kenghooi-teoh** [comment]
this example has since been removed, closing it
